# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'LxMusicMobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'LxMusicMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        next unless build_config.name == 'Debug'

        definitions = build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        definitions = [definitions] unless definitions.is_a?(Array)

        if target.name.start_with?('React-') || target.name == 'ReactCommon'
          definitions << 'RCT_DEV_SETTINGS_ENABLE_PACKAGER_CONNECTION=0' unless definitions.include?('RCT_DEV_SETTINGS_ENABLE_PACKAGER_CONNECTION=0')
          definitions << 'RCT_ENABLE_LOADING_FROM_PACKAGER=0' unless definitions.include?('RCT_ENABLE_LOADING_FROM_PACKAGER=0')
        end

        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions
      end

      next unless ['fmt', 'Flipper-Fmt'].include?(target.name)

      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        definitions = build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        definitions = [definitions] unless definitions.is_a?(Array)
        definitions << 'FMT_USE_CHAR8_T=0' unless definitions.include?('FMT_USE_CHAR8_T=0')
        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions
      end
    end

    fmt_header_path = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'core.h')
    if File.exist?(fmt_header_path)
      content = File.read(fmt_header_path)
      patched = content.gsub("namespace std {\ntemplate <> struct char_traits<fmt::internal::char8_type> : char_traits<char> {\n  using char_type = fmt::internal::char8_type;\n  static size_t length(const char_type* s) {\n    size_t len = 0;\n    while (s[len] != 0) ++len;\n    return len;\n  }\n};\n}  // namespace std\n\n", "")
      patched = patched.gsub("enum char8_type : unsigned char {};",
        "using char8_type = unsigned char;")
      patched = patched.gsub("using char8_type = char;",
        "using char8_type = unsigned char;")
      if !patched.include?("template <> struct char_traits<unsigned char>")
        patched = patched.gsub("#include <vector>\n\n",
          "#include <vector>\n\nnamespace std {\ntemplate <> struct char_traits<unsigned char> : char_traits<char> {\n  using char_type = unsigned char;\n  static size_t length(const char_type* s) {\n    size_t len = 0;\n    while (s[len] != 0) ++len;\n    return len;\n  }\n};\n}  // namespace std\n\n")
      end
      patched = patched.gsub("  basic_string_view(const Char* s)\n      : data_(s), size_(std::char_traits<Char>::length(s)) {}",
        "  basic_string_view(const Char* s)\n      : data_(s), size_(0) {\n    while (s[size_] != 0) ++size_;\n  }")
      if patched != content
        File.chmod(0644, fmt_header_path)
        File.write(fmt_header_path, patched)
      end
    end

    fmt_format_path = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'format.h')
    if File.exist?(fmt_format_path)
      content = File.read(fmt_format_path)
      if content.include?("using char8_type = char;")
        patched = content.gsub("using char8_type = char;", "enum char8_type : unsigned char {};")
      else
        patched = content
      end
      if patched != content
        File.chmod(0644, fmt_format_path)
        File.write(fmt_format_path, patched)
      end
    end
  end
end
